// Generated by gencpp from file sentence_voice/ListenRequest.msg
// DO NOT EDIT!


#ifndef SENTENCE_VOICE_MESSAGE_LISTENREQUEST_H
#define SENTENCE_VOICE_MESSAGE_LISTENREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sentence_voice
{
template <class ContainerAllocator>
struct ListenRequest_
{
  typedef ListenRequest_<ContainerAllocator> Type;

  ListenRequest_()
    : header()
    , duration(0)  {
    }
  ListenRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , duration(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::sentence_voice::ListenRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentence_voice::ListenRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListenRequest_

typedef ::sentence_voice::ListenRequest_<std::allocator<void> > ListenRequest;

typedef boost::shared_ptr< ::sentence_voice::ListenRequest > ListenRequestPtr;
typedef boost::shared_ptr< ::sentence_voice::ListenRequest const> ListenRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentence_voice::ListenRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentence_voice::ListenRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentence_voice::ListenRequest_<ContainerAllocator1> & lhs, const ::sentence_voice::ListenRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentence_voice::ListenRequest_<ContainerAllocator1> & lhs, const ::sentence_voice::ListenRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentence_voice

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentence_voice::ListenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentence_voice::ListenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentence_voice::ListenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentence_voice::ListenRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentence_voice::ListenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentence_voice::ListenRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentence_voice::ListenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60c27898c43a606374229cf5d04e89e3";
  }

  static const char* value(const ::sentence_voice::ListenRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60c27898c43a6063ULL;
  static const uint64_t static_value2 = 0x74229cf5d04e89e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentence_voice::ListenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentence_voice/ListenRequest";
  }

  static const char* value(const ::sentence_voice::ListenRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentence_voice::ListenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 发送的请求为持续听的时间\n"
"std_msgs/Header header\n"
"int16 duration\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sentence_voice::ListenRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentence_voice::ListenRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListenRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentence_voice::ListenRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentence_voice::ListenRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "duration: ";
    Printer<int16_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTENCE_VOICE_MESSAGE_LISTENREQUEST_H
