// Generated by gencpp from file sentence_voice/Listen.msg
// DO NOT EDIT!


#ifndef SENTENCE_VOICE_MESSAGE_LISTEN_H
#define SENTENCE_VOICE_MESSAGE_LISTEN_H

#include <ros/service_traits.h>


#include <sentence_voice/ListenRequest.h>
#include <sentence_voice/ListenResponse.h>


namespace sentence_voice
{

struct Listen
{

typedef ListenRequest Request;
typedef ListenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Listen
} // namespace sentence_voice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sentence_voice::Listen > {
  static const char* value()
  {
    return "9960a830d15d58a17858801d6d464529";
  }

  static const char* value(const ::sentence_voice::Listen&) { return value(); }
};

template<>
struct DataType< ::sentence_voice::Listen > {
  static const char* value()
  {
    return "sentence_voice/Listen";
  }

  static const char* value(const ::sentence_voice::Listen&) { return value(); }
};


// service_traits::MD5Sum< ::sentence_voice::ListenRequest> should match
// service_traits::MD5Sum< ::sentence_voice::Listen >
template<>
struct MD5Sum< ::sentence_voice::ListenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sentence_voice::Listen >::value();
  }
  static const char* value(const ::sentence_voice::ListenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentence_voice::ListenRequest> should match
// service_traits::DataType< ::sentence_voice::Listen >
template<>
struct DataType< ::sentence_voice::ListenRequest>
{
  static const char* value()
  {
    return DataType< ::sentence_voice::Listen >::value();
  }
  static const char* value(const ::sentence_voice::ListenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sentence_voice::ListenResponse> should match
// service_traits::MD5Sum< ::sentence_voice::Listen >
template<>
struct MD5Sum< ::sentence_voice::ListenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sentence_voice::Listen >::value();
  }
  static const char* value(const ::sentence_voice::ListenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentence_voice::ListenResponse> should match
// service_traits::DataType< ::sentence_voice::Listen >
template<>
struct DataType< ::sentence_voice::ListenResponse>
{
  static const char* value()
  {
    return DataType< ::sentence_voice::Listen >::value();
  }
  static const char* value(const ::sentence_voice::ListenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENTENCE_VOICE_MESSAGE_LISTEN_H
