// Generated by gencpp from file sentence_voice/Speak.msg
// DO NOT EDIT!


#ifndef SENTENCE_VOICE_MESSAGE_SPEAK_H
#define SENTENCE_VOICE_MESSAGE_SPEAK_H

#include <ros/service_traits.h>


#include <sentence_voice/SpeakRequest.h>
#include <sentence_voice/SpeakResponse.h>


namespace sentence_voice
{

struct Speak
{

typedef SpeakRequest Request;
typedef SpeakResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Speak
} // namespace sentence_voice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sentence_voice::Speak > {
  static const char* value()
  {
    return "6ec12d5a2bfa19afaef4554a69aed1b2";
  }

  static const char* value(const ::sentence_voice::Speak&) { return value(); }
};

template<>
struct DataType< ::sentence_voice::Speak > {
  static const char* value()
  {
    return "sentence_voice/Speak";
  }

  static const char* value(const ::sentence_voice::Speak&) { return value(); }
};


// service_traits::MD5Sum< ::sentence_voice::SpeakRequest> should match
// service_traits::MD5Sum< ::sentence_voice::Speak >
template<>
struct MD5Sum< ::sentence_voice::SpeakRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sentence_voice::Speak >::value();
  }
  static const char* value(const ::sentence_voice::SpeakRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentence_voice::SpeakRequest> should match
// service_traits::DataType< ::sentence_voice::Speak >
template<>
struct DataType< ::sentence_voice::SpeakRequest>
{
  static const char* value()
  {
    return DataType< ::sentence_voice::Speak >::value();
  }
  static const char* value(const ::sentence_voice::SpeakRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sentence_voice::SpeakResponse> should match
// service_traits::MD5Sum< ::sentence_voice::Speak >
template<>
struct MD5Sum< ::sentence_voice::SpeakResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sentence_voice::Speak >::value();
  }
  static const char* value(const ::sentence_voice::SpeakResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentence_voice::SpeakResponse> should match
// service_traits::DataType< ::sentence_voice::Speak >
template<>
struct DataType< ::sentence_voice::SpeakResponse>
{
  static const char* value()
  {
    return DataType< ::sentence_voice::Speak >::value();
  }
  static const char* value(const ::sentence_voice::SpeakResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENTENCE_VOICE_MESSAGE_SPEAK_H
