// Generated by gencpp from file judge_arrive/judge_arrive.msg
// DO NOT EDIT!


#ifndef JUDGE_ARRIVE_MESSAGE_JUDGE_ARRIVE_H
#define JUDGE_ARRIVE_MESSAGE_JUDGE_ARRIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace judge_arrive
{
template <class ContainerAllocator>
struct judge_arrive_
{
  typedef judge_arrive_<ContainerAllocator> Type;

  judge_arrive_()
    : x(0.0)
    , y(0.0)  {
    }
  judge_arrive_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::judge_arrive::judge_arrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::judge_arrive::judge_arrive_<ContainerAllocator> const> ConstPtr;

}; // struct judge_arrive_

typedef ::judge_arrive::judge_arrive_<std::allocator<void> > judge_arrive;

typedef boost::shared_ptr< ::judge_arrive::judge_arrive > judge_arrivePtr;
typedef boost::shared_ptr< ::judge_arrive::judge_arrive const> judge_arriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::judge_arrive::judge_arrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::judge_arrive::judge_arrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::judge_arrive::judge_arrive_<ContainerAllocator1> & lhs, const ::judge_arrive::judge_arrive_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::judge_arrive::judge_arrive_<ContainerAllocator1> & lhs, const ::judge_arrive::judge_arrive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace judge_arrive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::judge_arrive::judge_arrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::judge_arrive::judge_arrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::judge_arrive::judge_arrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::judge_arrive::judge_arrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::judge_arrive::judge_arrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::judge_arrive::judge_arrive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::judge_arrive::judge_arrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::judge_arrive::judge_arrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::judge_arrive::judge_arrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "judge_arrive/judge_arrive";
  }

  static const char* value(const ::judge_arrive::judge_arrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::judge_arrive::judge_arrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::judge_arrive::judge_arrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::judge_arrive::judge_arrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct judge_arrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::judge_arrive::judge_arrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::judge_arrive::judge_arrive_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUDGE_ARRIVE_MESSAGE_JUDGE_ARRIVE_H
