// Generated by gencpp from file vision/LeaderDistResponse.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_LEADERDISTRESPONSE_H
#define VISION_MESSAGE_LEADERDISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct LeaderDistResponse_
{
  typedef LeaderDistResponse_<ContainerAllocator> Type;

  LeaderDistResponse_()
    : distance(0.0)  {
    }
  LeaderDistResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::vision::LeaderDistResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::LeaderDistResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LeaderDistResponse_

typedef ::vision::LeaderDistResponse_<std::allocator<void> > LeaderDistResponse;

typedef boost::shared_ptr< ::vision::LeaderDistResponse > LeaderDistResponsePtr;
typedef boost::shared_ptr< ::vision::LeaderDistResponse const> LeaderDistResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::LeaderDistResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::LeaderDistResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::LeaderDistResponse_<ContainerAllocator1> & lhs, const ::vision::LeaderDistResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::LeaderDistResponse_<ContainerAllocator1> & lhs, const ::vision::LeaderDistResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::LeaderDistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::LeaderDistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::LeaderDistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::LeaderDistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::LeaderDistResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::LeaderDistResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::LeaderDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::vision::LeaderDistResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::LeaderDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/LeaderDistResponse";
  }

  static const char* value(const ::vision::LeaderDistResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::LeaderDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n"
;
  }

  static const char* value(const ::vision::LeaderDistResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::LeaderDistResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeaderDistResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::LeaderDistResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::LeaderDistResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_LEADERDISTRESPONSE_H
