; Auto-generated. Do not edit!


(cl:in-package general_service_2022-msg)


;//! \htmlinclude Goals_name.msg.html

(cl:defclass <Goals_name> (roslisp-msg-protocol:ros-message)
  ((name
    :reader name
    :initarg :name
    :type cl:string
    :initform "")
   (goal
    :reader goal
    :initarg :goal
    :type move_base_msgs-msg:MoveBaseGoal
    :initform (cl:make-instance 'move_base_msgs-msg:MoveBaseGoal)))
)

(cl:defclass Goals_name (<Goals_name>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Goals_name>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Goals_name)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name general_service_2022-msg:<Goals_name> is deprecated: use general_service_2022-msg:Goals_name instead.")))

(cl:ensure-generic-function 'name-val :lambda-list '(m))
(cl:defmethod name-val ((m <Goals_name>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader general_service_2022-msg:name-val is deprecated.  Use general_service_2022-msg:name instead.")
  (name m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <Goals_name>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader general_service_2022-msg:goal-val is deprecated.  Use general_service_2022-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Goals_name>) ostream)
  "Serializes a message object of type '<Goals_name>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'name))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Goals_name>) istream)
  "Deserializes a message object of type '<Goals_name>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Goals_name>)))
  "Returns string type for a message object of type '<Goals_name>"
  "general_service_2022/Goals_name")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Goals_name)))
  "Returns string type for a message object of type 'Goals_name"
  "general_service_2022/Goals_name")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Goals_name>)))
  "Returns md5sum for a message object of type '<Goals_name>"
  "5cba7b659cc9365a03ae2db68587ae95")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Goals_name)))
  "Returns md5sum for a message object of type 'Goals_name"
  "5cba7b659cc9365a03ae2db68587ae95")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Goals_name>)))
  "Returns full string definition for message of type '<Goals_name>"
  (cl:format cl:nil "string name~%move_base_msgs/MoveBaseGoal goal~%================================================================================~%MSG: move_base_msgs/MoveBaseGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Goals_name)))
  "Returns full string definition for message of type 'Goals_name"
  (cl:format cl:nil "string name~%move_base_msgs/MoveBaseGoal goal~%================================================================================~%MSG: move_base_msgs/MoveBaseGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Goals_name>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'name))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Goals_name>))
  "Converts a ROS message object to a list"
  (cl:list 'Goals_name
    (cl:cons ':name (name msg))
    (cl:cons ':goal (goal msg))
))
