// Generated by gencpp from file general_service_2022/Goals_name.msg
// DO NOT EDIT!


#ifndef GENERAL_SERVICE_2022_MESSAGE_GOALS_NAME_H
#define GENERAL_SERVICE_2022_MESSAGE_GOALS_NAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <move_base_msgs/MoveBaseGoal.h>

namespace general_service_2022
{
template <class ContainerAllocator>
struct Goals_name_
{
  typedef Goals_name_<ContainerAllocator> Type;

  Goals_name_()
    : name()
    , goal()  {
    }
  Goals_name_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::move_base_msgs::MoveBaseGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::general_service_2022::Goals_name_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_service_2022::Goals_name_<ContainerAllocator> const> ConstPtr;

}; // struct Goals_name_

typedef ::general_service_2022::Goals_name_<std::allocator<void> > Goals_name;

typedef boost::shared_ptr< ::general_service_2022::Goals_name > Goals_namePtr;
typedef boost::shared_ptr< ::general_service_2022::Goals_name const> Goals_nameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_service_2022::Goals_name_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_service_2022::Goals_name_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_service_2022::Goals_name_<ContainerAllocator1> & lhs, const ::general_service_2022::Goals_name_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_service_2022::Goals_name_<ContainerAllocator1> & lhs, const ::general_service_2022::Goals_name_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_service_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_service_2022::Goals_name_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_service_2022::Goals_name_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_service_2022::Goals_name_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_service_2022::Goals_name_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_service_2022::Goals_name_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_service_2022::Goals_name_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_service_2022::Goals_name_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cba7b659cc9365a03ae2db68587ae95";
  }

  static const char* value(const ::general_service_2022::Goals_name_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cba7b659cc9365aULL;
  static const uint64_t static_value2 = 0x03ae2db68587ae95ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_service_2022::Goals_name_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_service_2022/Goals_name";
  }

  static const char* value(const ::general_service_2022::Goals_name_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_service_2022::Goals_name_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"move_base_msgs/MoveBaseGoal goal\n"
"================================================================================\n"
"MSG: move_base_msgs/MoveBaseGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PoseStamped target_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::general_service_2022::Goals_name_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_service_2022::Goals_name_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goals_name_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_service_2022::Goals_name_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_service_2022::Goals_name_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::move_base_msgs::MoveBaseGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_SERVICE_2022_MESSAGE_GOALS_NAME_H
