// Generated by gencpp from file general_service_2022/YoloResult.msg
// DO NOT EDIT!


#ifndef GENERAL_SERVICE_2022_MESSAGE_YOLORESULT_H
#define GENERAL_SERVICE_2022_MESSAGE_YOLORESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <std_msgs/String.h>

namespace general_service_2022
{
template <class ContainerAllocator>
struct YoloResult_
{
  typedef YoloResult_<ContainerAllocator> Type;

  YoloResult_()
    : header()
    , image()
    , result()  {
    }
  YoloResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image(_alloc)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::std_msgs::String_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::general_service_2022::YoloResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_service_2022::YoloResult_<ContainerAllocator> const> ConstPtr;

}; // struct YoloResult_

typedef ::general_service_2022::YoloResult_<std::allocator<void> > YoloResult;

typedef boost::shared_ptr< ::general_service_2022::YoloResult > YoloResultPtr;
typedef boost::shared_ptr< ::general_service_2022::YoloResult const> YoloResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_service_2022::YoloResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_service_2022::YoloResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_service_2022::YoloResult_<ContainerAllocator1> & lhs, const ::general_service_2022::YoloResult_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image == rhs.image &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_service_2022::YoloResult_<ContainerAllocator1> & lhs, const ::general_service_2022::YoloResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_service_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_service_2022::YoloResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_service_2022::YoloResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_service_2022::YoloResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_service_2022::YoloResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_service_2022::YoloResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_service_2022::YoloResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_service_2022::YoloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1b7078dec013296b04efb925d9d4b21";
  }

  static const char* value(const ::general_service_2022::YoloResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1b7078dec013296ULL;
  static const uint64_t static_value2 = 0xb04efb925d9d4b21ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_service_2022::YoloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_service_2022/YoloResult";
  }

  static const char* value(const ::general_service_2022::YoloResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_service_2022::YoloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/Image image\n"
"std_msgs/String result\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::general_service_2022::YoloResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_service_2022::YoloResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_service_2022::YoloResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_service_2022::YoloResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "result: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_SERVICE_2022_MESSAGE_YOLORESULT_H
